steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/f1-dashboard-493015/f1-backend'
      - '-f'
      - 'Dockerfile.backend'
      - '.'

  # 2. Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/f1-dashboard-493015/f1-backend'

  # 3. Deploy the newly pushed image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'f1-backend'
      - '--image'
      - 'gcr.io/f1-dashboard-493015/f1-backend'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--quiet'

images:
  - 'gcr.io/f1-dashboard-493015/f1-backend'

options:
  logging: CLOUD_LOGGING_ONLY

