"""CP75's follow-up question chips — generated by the model, cleared by the router.

Three or four suggested next questions render under a finished answer, and
clicking one sends it as if the reader had typed it. That last part is the
whole design problem: **a chip is a promise.** A suggestion this app's tools
cannot answer does not degrade politely — it is a button that produces a
refusal, an "I don't have web access" apology, or a wandering turn that burns
a free-tier slot, and the reader's own click is what triggered it. So this
module is deliberately two halves that do not trust each other:

- `suggest` asks the model for candidates. Model-generated was the explicit
  choice, made knowing the cheaper alternative was deriving chips from the
  tools that ran (zero inference). The model sees the question and its own
  answer, so it can suggest the thing a reader would actually wonder next
  ("what about qualifying?") rather than a template.
- `routable` throws candidates away. It is pure Python — `router.classify`
  plus `guardrails.check_input`, the two model-free gates `main.py` already
  runs on every real question — and it is the *only* reason a suggestion
  reaches the screen. This is CP38/CP41/CP44's rule again: do not ask the
  model to restrict itself to answerable questions, check it in code.

**Fewer chips is a fine outcome; a dead-end chip is not.** Every failure
here — no key, a timeout, a refusal, unparseable output, or all four
candidates dropped by the router — returns `[]`, and `[]` renders nothing.
The feature is additive; it must never break or delay a turn.

## Why the generation call is where it is

`concurrency.py`'s gate admits exactly one run because Ollama Cloud's free
tier serves exactly one concurrent model, and `--max-instances=1` is the
other half of that mechanism. A second model call is therefore not free of
consequences even when it is cheap: fired *outside* the slot it would race
whatever the gate admitted next, which is the precise failure the gate exists
to prevent, and fired *before* `done` it would delay the answer the reader is
already waiting on.

`main.py` resolves that by holding the run slot open across `done` (see the
`AsyncExitStack` there) and calling `suggest` in the gap between emitting
`done` and releasing the slot. The reader has their whole answer, its sources
and its `done` event before this module runs at all; the gate is still held,
so nothing else is talking to Ollama; and the bounded timeout below caps how
long the *next* asker can be kept waiting by someone else's chips.

## Why the model is asked for one buffered, unstructured reply

`model.chat` (not `stream_chat`, not a `deepagents` graph): there is nothing
to stream to, no tools to bind, and no evidence to cite — the output is four
short strings. A graph would cost tool-schema tokens and a step budget for a
task with no tools in it. And the reply is parsed line-by-line rather than as
JSON on purpose: CP44's lesson is that a documented output format is not a
produced one, and a model that wraps its JSON in prose would cost us every
chip. A newline-separated list degrades gracefully — a malformed line is one
dropped candidate, not a dropped feature.
"""

from __future__ import annotations

import asyncio
import re

from . import config, guardrails, model as model_seam, router

MAX_SUGGESTIONS = 4
"""Ceiling on rendered chips. The design says "three to four"; the model is
asked for four and the router usually drops one, which lands there naturally
without a filler mechanism that would have to invent an unvalidated chip."""

TIMEOUT_SECONDS = 12.0
"""Wall clock for the whole generation call.

Not `config.REQUEST_TIMEOUT_SECONDS` (180s), which is sized for an agent turn
that may make a dozen tool calls. This is one short completion, and the cost
of overrunning is paid by the *next* person in the queue — `main.py` is still
holding the run slot while this waits. Twelve seconds is generous for four
one-line strings and cheap to lose entirely when it is not."""

MAX_QUESTION_CHARS = 120
"""Longest suggestion that still reads as a chip rather than a paragraph.
Also a cheap sanity gate: a model that ignores the format and returns prose
produces one very long "question", which this drops."""

MIN_QUESTION_CHARS = 12

_ANSWER_EXCERPT_CHARS = 1200
"""How much of the answer the model is shown. The suggestions only need the
answer's *subject matter*, and this runs on a GPU-time-metered plan where the
prompt is billed as surely as the completion — a 4000-character season recap
would triple the cost of generating four short strings for no measurable
gain."""

SUGGESTION_PROMPT = """You suggest follow-up questions for an F1 analysis app.

Given a question a reader just asked and the answer they received, write
exactly 4 short follow-up questions they would plausibly ask next.

Rules:
- Each question must be answerable from this app's own Formula 1 database:
  race results, qualifying, standings, drivers, constructors, circuits, pit
  stops, lap times, strategy and history from 1950 to today.
- Never suggest anything needing live news, rumours, transfers, contracts,
  future regulations, or a prediction about a race that has not happened.
- Never ask for an opinion ("who is the greatest") — only facts this app
  can look up.
- Each question must stand on its own. A reader clicking it sends it as a
  fresh question, so "what about him?" is useless — name the driver, the
  team, the season or the race explicitly.
- Do not repeat the question that was just asked.
- Keep each under 100 characters.

Output ONLY the 4 questions, one per line, with no numbering, no bullets, no
quotes and no other text."""

_LEADING_ORNAMENT = re.compile(r"^\s*(?:[-*•–—]|\d+[.)])\s*")
"""Numbering and bullets the prompt asked for and will sometimes get anyway.
Stripped rather than treated as a format violation — the question after the
bullet is perfectly good, and CP41 already recorded what happens when this
codebase relies on a model honouring a prompt-stated ban."""

_WHITESPACE = re.compile(r"\s+")


def _clean(line: str) -> str:
    """One raw output line, reduced to a bare question or to ``""``.

    Surrounding quotes are stripped because a model asked for plain lines
    quotes them roughly half the time, and a chip reading `"Who won?"` with
    visible quotation marks looks like a bug in the UI rather than a
    suggestion.
    """
    text = _LEADING_ORNAMENT.sub("", line or "")
    text = _WHITESPACE.sub(" ", text).strip()
    text = text.strip("\"'“”‘’").strip()
    return text


_IMPERATIVE_OPENERS = (
    "compare ",
    "show ",
    "list ",
    "tell me ",
    "explain ",
    "walk me ",
    "summarize ",
    "summarise ",
)
"""Openers that make a chip a legitimate ask without a question mark.

Not invented for this module: CP70's own contextual prompts are written this
way ("Compare Verstappen and Norris this season", "Walk me through this
race's key moments", "Summarize the race control messages so far"), and CP75's
chips are the post-answer equivalent of that surface. Requiring a literal "?"
would have rejected the house style."""


def _looks_like_a_question(text: str) -> bool:
    """Is this something a reader could plausibly have typed into the box?

    A trailing colon is the tell for a heading or a preamble and is rejected
    outright; otherwise a chip must either be interrogative or open with one
    of `_IMPERATIVE_OPENERS`. The full-width "？" is accepted alongside the
    ASCII one for the same reason CP73 widened the citation parser to accept
    `【ev_2】`: the deployed model demonstrably emits full-width punctuation,
    and being blind to it costs a perfectly good chip.
    """
    lowered = text.casefold()
    if lowered.endswith(":"):
        return False
    return text.endswith(("?", "？")) or lowered.startswith(_IMPERATIVE_OPENERS)


def routable(question: str) -> bool:
    """Can this app actually answer this suggestion? The non-negotiable guard.

    Pure Python — no model, no network — and made of the two gates a real
    question already passes through in `main.py`, rather than a third set of
    rules that could drift away from them:

    1. **`guardrails.check_input`.** A suggestion this refuses would produce
       an SSE `refused` event the instant it were clicked. That is not a
       hypothetical: the scope guard rejects anything it cannot recognise as
       an F1 question, and a model improvising follow-ups drifts out of scope
       (motorsport-adjacent, or a question about the app itself) more readily
       than a human asker does.

    2. **`router.classify`.** Two of the `Route` it returns are dead ends for
       a chip, for reasons the router itself already documents:

       - **Tier 3** is the live-web class — news, rumours, transfers, future
         regulations, predictions, seasons this app's calendar does not
         cover. `graph.SYSTEM_PROMPT` states plainly that this build has no
         web access and instructs the model to say so; a chip promising next
         year's regulations is therefore a button whose only possible outcome
         is that apology.
       - **`route.subjective`** — "better than", "greatest ever", "GOAT". No
         tool in this app returns a verdict, and CP64's framing contract
         exists precisely because the model answering one anyway is a known
         failure. A fact the reader can click is the point of a chip; an
         opinion is not.

       Tier 1 and non-subjective tier 2 both route to the flat graph with the
       full internal toolset bound, which is exactly the surface these
       suggestions are supposed to stay inside.

    The shape checks above those two are not routing rules and are not
    pretending to be; they keep a stray heading or a paragraph of prose from
    being handed to the router at all. `_looks_like_a_question` earns its
    place because the scope guard cannot do its job: a model asked for a bare
    list routinely prefixes it with "Here are your follow-up questions:", and
    the scope guard — generous by design, to avoid false positives on real F1
    questions (`guardrails/scope.py`) — allows that line straight through. A
    preamble is not something a reader can ask.
    """
    text = (question or "").strip()
    if not (MIN_QUESTION_CHARS <= len(text) <= MAX_QUESTION_CHARS):
        return False
    if not _looks_like_a_question(text):
        return False
    if not guardrails.check_input(text).allowed:
        return False
    route = router.classify(text)
    if route.tier >= 3 or route.subjective:
        return False
    return True


def parse(raw: str, *, asked: str = "", limit: int = MAX_SUGGESTIONS) -> list[str]:
    """Turn a raw completion into the chips that survive `routable`.

    Split out from `suggest` so the validation path is testable without a
    model, which is where the checkpoint's real risk lives: the generation
    call is a one-liner around an existing seam, but "unroutable suggestions
    are dropped" is the promise the feature rests on.

    De-duplication is case-insensitive and includes the question that was just
    asked — a model handed its own answer will re-suggest the question that
    produced it often enough that leaving it in reads as the panel not
    listening.
    """
    seen: set[str] = {(asked or "").strip().casefold()}
    out: list[str] = []
    for line in (raw or "").splitlines():
        candidate = _clean(line)
        key = candidate.casefold()
        if not candidate or key in seen:
            continue
        if not routable(candidate):
            continue
        seen.add(key)
        out.append(candidate)
        if len(out) >= limit:
            break
    return out


async def suggest(question: str, answer: str, *, limit: int = MAX_SUGGESTIONS) -> list[str]:
    """Follow-up chips for a finished turn, or `[]` for every kind of failure.

    Total by construction. `model.chat` raises a typed `ModelError` for a
    missing key, exhausted quota, a transport failure and an empty reply, and
    every one of those means the same thing here — the reader gets their
    answer with no chips under it, which is indistinguishable from a turn
    where the router happened to drop all four. That is the intended
    behaviour, not a swallowed bug: `main.py`'s except chain owns turn-level
    failures, and an optional surface that could break a turn would be worse
    than no surface. The one thing this does not swallow is
    `asyncio.CancelledError` — a client disconnect must keep propagating so
    the run slot is released immediately rather than after this timeout.

    Skipped entirely without an API key so a local run with no secrets pays
    nothing for a feature that cannot work.
    """
    if not config.api_key():
        return []
    text = (question or "").strip()
    draft = (answer or "").strip()
    if not text or not draft:
        return []

    try:
        async with asyncio.timeout(TIMEOUT_SECONDS):
            message = await model_seam.chat(
                [
                    {"role": "system", "content": SUGGESTION_PROMPT},
                    {
                        "role": "user",
                        "content": (
                            f"Question asked:\n{text}\n\n"
                            f"Answer given:\n{draft[:_ANSWER_EXCERPT_CHARS]}"
                        ),
                    },
                ]
            )
    except asyncio.CancelledError:
        raise
    except Exception as error:  # noqa: BLE001 - additive surface, fails silent
        print(f"follow-up suggestions skipped: {type(error).__name__}: {error}")
        return []

    # `content` is the only field read: `model.py`'s module docstring is
    # explicit that a reasoning model's sibling `thinking` field must never be
    # forwarded, and a chip built out of chain-of-thought would be exactly
    # that leak in a new surface.
    return parse((message or {}).get("content") or "", asked=text, limit=limit)
